image: java:openjdk-8-jdk

before_script:
  - apt-get update
  - apt-get install -y apt-transport-https
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update
  - apt-get install -y scala sbt

stages:
  - build
  - test

job1:
  stage: build
  script:
    - sbt test
  tags:
    - docker
